import LogdetLean.Coherence.MovingHCurtissPositiveMass

#print axioms LogdetLean.Coherence.paperFiniteMeasureGaussianCDFApproximation_of_positiveMass
#print axioms LogdetLean.Coherence.paperFiniteMeasureCurtissBridge_of_positiveMass
#print axioms LogdetLean.Coherence.eventually_exactVoidFactor_ge_pos_of_M3_P1
#print axioms LogdetLean.Coherence.eventually_leadingVoidMeasure_mass_ge_pos_of_M3_P1_laplace
