import LogdetLean.VonNeumannTypicality

/-! Permanent aggregate audit for the von Neumann typicality development. -/

#print axioms LogdetLean.VonNeumannTypicality.hasDerivAt_entropyProfile
#print axioms LogdetLean.VonNeumannTypicality.abs_deriv_entropyProfile_le_log_exp_div
#print axioms LogdetLean.VonNeumannTypicality.abs_regularizedEntropyProfile_sub_le
#print axioms LogdetLean.VonNeumannTypicality.renyiTwoSpectralStatistic_lower_bound
#print axioms LogdetLean.VonNeumannTypicality.abs_regularizedEntropySpectralStatistic_sub_le_ltwo
#print axioms LogdetLean.VonNeumannTypicality.log_le_bosonicEntropy
#print axioms LogdetLean.VonNeumannTypicality.entropyProfile_endpoint_le_power
#print axioms LogdetLean.VonNeumannTypicality.tendsto_nat_mul_entropyProfile_inverseSquareCutoff
#print axioms LogdetLean.VonNeumannTypicality.tendsto_entropySpectralStatistic_sub_regularized_inverseSquareCutoff
#print axioms LogdetLean.VonNeumannTypicality.tendsto_entropySpectralStatistic_cutoff_error_div_normalizer
#print axioms LogdetLean.VonNeumannTypicality.integral_entropySpectralStatistic_energy_lower_bound
#print axioms LogdetLean.VonNeumannTypicality.entropyMean_tendsto_atTop_of_energyMean
#print axioms LogdetLean.VonNeumannTypicality.relative_deviation_lt_of_approximation
#print axioms LogdetLean.VonNeumannTypicality.tendsto_ratio_one_of_tendsto_sub_zero
#print axioms LogdetLean.VonNeumannTypicality.weaklyTypical_of_uniform_approximation
#print axioms LogdetLean.VonNeumannTypicality.weaklyTypical_entropySpectralStatistic_of_regularized
#print axioms LogdetLean.VonNeumannTypicality.truncatedCOEBlock_eq_mul_transpose
#print axioms LogdetLean.VonNeumannTypicality.truncatedCOEBlock_isSymm
#print axioms LogdetLean.VonNeumannTypicality.truncatedCOEBlock_smul
#print axioms LogdetLean.VonNeumannTypicality.truncatedCOEDefectEnergy_eq
#print axioms LogdetLean.VonNeumannTypicality.integral_matrixDefectEnergy_of_coeSecondMoments
#print axioms LogdetLean.VonNeumannTypicality.coeExpectedDefect_tendsto_atTop

/-! Audited extensions added in the 2026-08-15 proof review. -/
#print axioms LogdetLean.VonNeumannTypicality.tendsto_entropySpectralStatistic_cutoff_error_div_normalizer_variableDimension
#print axioms LogdetLean.VonNeumannTypicality.weaklyTypical_entropySpectralStatistic_of_regularized_variableDimension
#print axioms LogdetLean.VonNeumannTypicality.weaklyTypical_physicalEntropy_of_regularized_singularValueStatistic
#print axioms LogdetLean.VonNeumannTypicality.covarianceCoupling_sq
#print axioms LogdetLean.VonNeumannTypicality.manuscriptSymplecticForm_mul_covarianceCoupling
#print axioms LogdetLean.VonNeumannTypicality.manuscript_omega_covariance_square
#print axioms LogdetLean.VonNeumannTypicality.measure_largeDeviation_le_regularized_largeDeviation
#print axioms LogdetLean.VonNeumannTypicality.ae_eventually_relative_error_lt_of_tsum_measure_ne_top
#print axioms LogdetLean.VonNeumannTypicality.ae_eventually_abs_centered_lt_mul_rpow_of_tsum_measure_ne_top
#print axioms LogdetLean.VonNeumannTypicality.variance_le_two_variance_add_two_sq_of_uniform_approximation
